config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get 'home' => 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'signup'=>'users#new'
  get 'login' => 'sessions#new'
  post 'login'=> 'sessions#create'
  delete 'logout' =>'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources  :account_activations,  only: [:edit]
  resources :password_resets, only: [:new,:create,:edit,:update]
  resources :microposts, only: [:create,:destroy]
  resources :relationships, only: [:create, :destroy]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
<div class="alert alert-danger">
The form contains <%= pluralize(object.errors.count, "error") %>.
</div>
<ul>
<% object.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>

<%= render @feed_items %>

<% end%>

app/views/shared/_homes.html.erb
<div class="container">
  <div class="jumbotron">
    <h1 align="center"> Welcome to Sample App!</h1>  
	<div align="center"><%= link_to "SignUp Here!",signup_path, class:"btn btn-default"%>
	<%= link_to "Already have account?",login_path, class:"btn btn-default" %>
	</div>    
    
  </div>
     
</div>

app/views/shared/_micropost_form.html.erb
<div align="left">
<%= form_for(@micropost, html: {multipart: true}) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div class="field">
<%= f.text_area :content, placeholder: "Compose new micropost..." %>
</div>
<span class="picture">
<%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png'%>
</span>
<br/>
<%= f.submit "Post", class: "btn btn-primary" %>
<% end %>
</div>

app/views/shared/_stats.html.erb
<div>
<% @user ||= current_user %>
<div class="stats">
<a href="<%= following_user_path(@user) %>">
<strong id="following" class="stat">
<%= @user.following.count %>
</strong>
following
</a>
<a href="<%= followers_user_path(@user) %>">
<strong id="followers" class="stat">
<%= @user.followers.count %>
</strong>
followers
</a>
</div>
</div>

app/views/shared/_user_info.html.erb
<div align="left">
<% if current_user.picture?%>
<img src="<%=current_user.picture.url%>" class="img-thumbnail" style="width:150px; height:150px">
<% else%>
<%= link_to gravatar_for(current_user), current_user %>
<%end%>
<h1><a href="<%= current_user%>"><%= current_user.name %></a></h1>

<span><%= pluralize(current_user.microposts.count, "micropost") %></span>
</div>