config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get 'home' => 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'signup'=>'users#new'
  get 'login' => 'sessions#new'
  post 'login'=> 'sessions#create'
  delete 'logout' =>'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources  :account_activations,  only: [:edit]
  resources :password_resets, only: [:new,:create,:edit,:update]
  resources :microposts, only: [:create,:destroy]
  resources :relationships, only: [:create, :destroy]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= yield(:title)%> </title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
	<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#"><b>SAMPLE APP</b></a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home",home_path %></li>
      <li><%= link_to "About",about_path %></li>
	  <li><%= link_to "Help",help_path %></li>
	  <% if logged_in?%>
	  <li> <%= link_to "Users", users_path %></li>
	  <li class="dropdown">
	  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	  <%= current_user.name%><b class="caret"></b>
	  </a>
	  <ul class="dropdown-menu">
	  <li> <%= link_to "Profile", current_user %></li>
	  <li> <%= link_to "Settings", edit_user_path(current_user) %></li>
	  <li class="divider"></li>
	  <li>
	  <%= link_to "Log Out", logout_path,  method: "delete" %>
	  </li>
	  </ul>
	  </li>
	  <% else %>
	  <li> <%= link_to "Log in", login_path %></li>
	  <% end%>

    </ul>
  </div>
</nav>
<% flash.each do |message_type,message|%>
<div class="alert alert-<%=message_type%> alert-dismissible"> 
<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
<%= message %></div>
<%end%>

<%=yield%>


<%= debug(params) if Rails.env.development? %>
  </body>
</html>